import type { Metadata } from "next";
import Providers from "./providers";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/theme";
import { PageLayout } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <ThemeProvider theme={theme} >
          <body>
            <PageLayout theme={theme}>
              {children}
            </PageLayout>
          </body>
        </ThemeProvider>
      </Providers>
    </html>
  );
}
