import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config'
import { ChakraProvider } from "@chakra-ui/react";
import { theme } from "@/theme";
import Provider from "@/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));

  return (
    <html lang="en">
      <body className={inter.className}>
          <Provider initalState={initialState}>
        <ChakraProvider theme={theme}>
            {children}
        </ChakraProvider>
          </Provider>
      </body>
    </html>
  );
}
